name: Functional (pip)

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - '.github/workflows/*.yml'
      - 'pyproject.toml'
      - 'setup.py'
      - 'setup.cfg'
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/*.yml'
      - 'pyproject.toml'
      - 'setup.py'
      - 'setup.cfg'

jobs:
  basic-functional-tests-using-pip:

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10', '3.11' ]

    steps:
    # STEP 1: Checkout the repository AND its submodules
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    # STEP 2: Install all OS-level dependencies, including build tools
    - name: Install OS dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin cmake build-essential

    # STEP 3: Set up the correct Python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # STEP 4: Build jigsawpy from source and install all packages
    - name: Install packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python ./submodules/jigsaw-python/build.py
        pip install ./submodules/jigsaw-python
        pip install .

    # STEP 5: Prepare the test data
    - name: Prepare example DEM
      run: |
        wget https://coast.noaa.gov/htdata/raster2/elevation/NCEI_ninth_Topobathy_2014_8483/northeast_sandy/ncei19_n40x75_w073x75_2015v1.tif -O /tmp/fullsize_dem.tif
        gdalwarp -tr 0.0005 0.0005 -r average -overwrite /tmp/fullsize_dem.tif /tmp/test_dem.tif

    # STEP 6: Run tests with the corrected library path logic
    - name: Run all tests
      run: |
        # Find the site-packages directory
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        # Search for the library file to get its full path
        LIB_FILE_PATH=$(find "${SITE_PACKAGES}" -name "libjigsaw.so")
        # Get the parent directory of the found file
        JIGSAW_LIB_PATH=$(dirname "${LIB_FILE_PATH}")
        # Export the correct library path so the OS can find libjigsaw.so
        export LD_LIBRARY_PATH="${JIGSAW_LIB_PATH}:${LD_LIBRARY_PATH}"

        # Run all test scripts in the correctly configured environment
        source tests/cli/build_geom.sh
        source tests/cli/build_hfun.sh
        source tests/cli/remesh_by_dem.sh
        python -m unittest discover tests/api -p "*.py"
